version: 2

env: &env
  GOOGLE_CLOUD_SDK_VERSION: 244.0.0
  GOOGLE_CLOUD_SDK_DOWNLOAD_PATH: /google-cloud-sdk
  GCP_PROJECT_ID: blog-lampetty-net-redirector

gitconfig: &gitconfig
  name: "Set .gitconfig"
  command: |
    echo "" > ~/.gitconfig
    git config --global url."https://github.com".insteadOf git://github.com
    git config --global http.https://gopkg.in.followRedirects true

jobs:
  test:
    working_directory: /go/src/github.com/oinume/blog-lampetty-net-redirector
    docker:
      - image: golang:1.12-stretch
    steps:
      - checkout
      - run:
          name: "Set .gitconfig"
          command: |
            echo "" > ~/.gitconfig
            git config --global url."https://github.com".insteadOf git://github.com
            git config --global http.https://gopkg.in.followRedirects true
      - run:
          name: "Install dep"
          command: |
            go get github.com/golang/dep/cmd/dep
      - restore_cache:
          key: go-dep-{{ checksum "Gopkg.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            if [ ! -e "/go/src/github.com/oinume/blog-lampetty-net-redirector/vendor" ]; then
              dep ensure
            fi
      - save_cache:
          key: go-dep-{{ checksum "Gopkg.lock" }}
          paths:
          - "/go/src/github.com/oinume/blog-lampetty-net-redirector/vendor"
#      - run:
#          name: "Run go-lint"
#          command: make go-lint
      - run:
          name: "Run test"
          command: |
            make test

  deploy-image:
    environment:
      <<: *env
    working_directory: /go/src/github.com/oinume/blog-lampetty-net-redirector
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - run:
          <<: *gitconfig
      - run:
          name: Install dependency apk packages
          command: |
            apk --no-cache add \
              bash \
              curl \
              curl-dev \
              make \
              python
      - restore_cache:
          key: google-cloud-sdk-244.0.0
      - run:
          name: "Install google-cloud-sdk"
          command: |
            ./ci/install-google-cloud-sdk.sh
      - save_cache:
          key: google-cloud-sdk-244.0.0
          paths:
            - /google-cloud-sdk
      - run:
          name: "Activate GCP service account"
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ./gcp-service-account-key.json
            gcloud auth activate-service-account --key-file ./gcp-service-account-key.json
      - run:
          name: "Deploy docker image to GCR"
          command: |
            TAG=$(echo "${CIRCLE_BRANCH}" | tr '._/' '-' | tr '[:upper:]' '[:lower:]')-"${CIRCLE_BUILD_NUM}"
            echo ${TAG}
            gcloud builds submit --project ${GCP_PROJECT_ID} \
              --tag gcr.io/${GCP_PROJECT_ID}/blog-lampetty-net-redirector:${TAG}

workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - deploy-image:
          requires:
            - test
          filters:
            branches:
              only: /.*/
