name: ci
on:
  - push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          make test
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          COMMIT=$(git describe --always --tag)
          BRANCH=$(basename ${GITHUB_REF})
          IMAGE_TAG=$(echo "${BRANCH}" | tr '._/' '-' | tr '[:upper:]' '[:lower:]')-"${COMMIT}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          make gcloud/builds IMAGE_TAG=${IMAGE_TAG}
      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy server \
            --quiet \
            --region us-central1 \
            --image "gcr.io/${GCP_PROJECT_ID}/server:${IMAGE_TAG}" \
            --platform managed \
            --allow-unauthenticated
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
