name: ci
on:
  - push
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    env:
      CACHE_VERSION: 1
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          make test
